SELECT child.ITEM_ID, child.ITEM_NAME, child.RARITY
FROM ITEM_INFO parent
JOIN ITEM_TREE tree
    ON parent.ITEM_ID = tree.PARENT_ITEM_ID
JOIN ITEM_INFO child
    ON tree.ITEM_ID = child.ITEM_ID
WHERE parent.RARITY = 'RARE'
ORDER BY child.ITEM_ID DESC;
